### ISSUE TITLE
Categories Controller and Base View

### ISSUE THREAD

**Issue by armstrhb** [armstrhb/Triumph#11]
Time to look at categories.  Create the **Categories Controller** with the following actions:
- [x] **index** - input: realm id.  Return the list of categories for the given realm id.
- [x] **show** - input: category id. Return the category. I'm thinking that the detail view should state the realm the category is owned by, and maybe the achievements that are within it.  Maybe even 5 users that have attained the most achievements with that category?
- [x] **rename** - input: category id and new name. Renames the category, and returns it over json.
- [x] **destroy** - input: category id.  Removes the category.  Done at the listing level. Once deleted, the entry is removed from the listing.

For each of these, let's get prototype views for each to demonstrate functionality.

**Comment by wallBMW** [comment]
Category controller complete. Index returns list of categories along with their description and realm.
