### ISSUE TITLE
Front end Color Scheme Brainstorming

### ISSUE THREAD

**Issue by armstrhb** [armstrhb/Triumph#21]
Let's brainstorm potential color schemes for triumph's front end. Link some color schemes in here, or maybe even images of the schemes, and we'll decide on the best.

**Comment by armstrhb** [comment]
Here's my first idea here.  This would be a light scheme. The muted orange and green/blue give a nice contrast.

![image](https://cloud.githubusercontent.com/assets/11358169/8219017/0b0cc3dc-1515-11e5-845a-4ac18ac0a534.png)

**Comment by armstrhb** [comment]
btw, [coolors.co](http://coolors.co/) is a pretty nice site for generating these.

**Comment by wallBMW** [comment]
Here is an idea. We should throw up lots of these to have many choices.

![capture](https://cloud.githubusercontent.com/assets/12076895/8222449/9cc45f46-1539-11e5-90e8-cb6ef87f4bc9.PNG)

**Comment by armstrhb** [comment]
![image](https://cloud.githubusercontent.com/assets/11358169/8222554/1d72edb4-153b-11e5-81b1-8be98713dadd.png)

**Comment by wallBMW** [comment]
![capture](https://cloud.githubusercontent.com/assets/12076895/8222631/dbcf8790-153b-11e5-822d-7678d8c60f3a.PNG)

**Comment by armstrhb** [comment]
i think having at least two contrasting colors will work good for us, otherwise we'll be monochrome, which might be too minimalist.

**Comment by armstrhb** [comment]
i think i like our first two best.

**Comment by wallBMW** [comment]
my last one 

![capture](https://cloud.githubusercontent.com/assets/12076895/8222833/8978346c-153e-11e5-9270-b4f6b13a9aca.PNG)

**Comment by armstrhb** [comment]
ok, my favorites are:

my first, your second. how about you?

**Comment by wallBMW** [comment]
I like your first. We will go with that.
