### ISSUE TITLE
Front end font choice brainstorming

### ISSUE THREAD

**Issue by armstrhb** [armstrhb/Triumph#22]
Let's discuss and review potential font choices for triumph's front end.

Let's decide on:
- One font? Multiple? (one for headings, one for paragraphs, one for achievement bars, etc.)
- Which one to use

Let's link to candidates, or even take screenshots of them.

**Comment by wallBMW** [comment]
Multiple fonts all the way. 

For the headings I found these two (just skimmed, not definite):

<ul>
<li>Nunito</li>
<li>Electrolize</li>
</ul>

![nunito](https://cloud.githubusercontent.com/assets/12076895/8214482/9c926564-14f7-11e5-85cf-dcd56df724ce.png)
![electrolize](https://cloud.githubusercontent.com/assets/12076895/8214486/a1e41224-14f7-11e5-9795-2085f718b386.png)

For paragraphs I really like the Lato font. Let me know what you think. There are tons of custom fonts out there and these are only a few. 
![lato](https://cloud.githubusercontent.com/assets/12076895/8214509/df8d0950-14f7-11e5-9893-ef60c04cee19.png)

How many fonts do we want? We should have a distinct font for the jumbotrons and for regular sentence text (lato). What else do you think we should find a font for?

**Comment by armstrhb** [comment]
I like those. Let's get a few more just so we have a few to decide from.  I
think we should definitely have heading and paragraph fonts, and maybe one
related to achievement bars. It'd be cool to have our progress bars to have
some extra work put in on styling.

**Comment by armstrhb** [comment]
Here's some more candidates for heading:

**Allerta**
![image](https://cloud.githubusercontent.com/assets/11358169/8218268/eb570bf6-150f-11e5-9b92-89503dd88e19.png)

**Atomic Age**
![image](https://cloud.githubusercontent.com/assets/11358169/8218296/14ee4dc6-1510-11e5-9c0e-203c0cf359ce.png)

**Cinzel**
![image](https://cloud.githubusercontent.com/assets/11358169/8218608/ebb164c8-1511-11e5-9bea-b799b48a600c.png)

**Khand**
![image](https://cloud.githubusercontent.com/assets/11358169/8218670/6b78a4c8-1512-11e5-919d-935be02b92a2.png)

**Nova Round**
![image](https://cloud.githubusercontent.com/assets/11358169/8218724/c93beae8-1512-11e5-817b-5bc2048fa76d.png)

**Signika**
![image](https://cloud.githubusercontent.com/assets/11358169/8218765/292ff82c-1513-11e5-95f1-3f589aaabef9.png)

**Comment by wallBMW** [comment]
I really like Nova Round, Electrolize, and Signika. Those are my top 3 choices.

**Comment by armstrhb** [comment]
i think i like nova round the most. it has the best personality for what we're after.

**Comment by wallBMW** [comment]
Nova round it is!

**Comment by armstrhb** [comment]
word! i'm good with lato for a paragraph font too.

**Comment by wallBMW** [comment]
Do we want one more font for progress?

**Comment by armstrhb** [comment]
let's work with these two and see which goes better with progress. we can discuss a third if neither fit.
