### ISSUE TITLE
Draft Rails Structure

### ISSUE THREAD

**Issue by armstrhb** [armstrhb/Triumph#5]
Rails is new to us. After some training, let's document how our rails app structure will look.  We'll need to list out:
- [x] Each Model
- [x] Each Controller (will be similar to model, but might have some extra for different types of viewng)
- [x] Database thoughts (what will we actually use? the built in SQLite? MySQL?)
- [x] Research how REST API interacts with controllers (different ones needed?)

Once these are worked through and identified, I'd say let's go ahead and start stubbing out the skeleton of this with rails.

**Comment by armstrhb** [comment]
@wallBMW let's concentrate on this one first. #3 and #4 will be successors of this one.

**Comment by armstrhb** [comment]
[Rails REST API Tutorial](https://www.airpair.com/ruby-on-rails/posts/building-a-restful-api-in-a-rails-application) might be worth looking at.

**Comment by wallBMW** [comment]
I need to have a better understanding of MVC stuff before I can make any suggestions but my opinion is that SQLite would suffice for what we need to do. 

Although it doesn't compare to other server/client RDBMs I read it could handle up to 500k http requests in a day easily.

**Comment by wallBMW** [comment]
I change my mind. MySQL is a better fit for a multi-user application (which I assume this is going to be). SQLite is also pretty weak when it comes to writes. Apparently only one write can be going on at any given time....lame. We are going to be needing a db that can support multiple users accessing it at the same time right?

**Comment by armstrhb** [comment]
yes, definitely.  SQLite will probably be fine for us while in development, but we need to make sure we're up to speed on pivoting between DB's (and testing them) when we get closer to a release.  From what I know of Ruby, it should be cake to pivot though.

Here's a link for [Rails MVC](http://betterexplained.com/articles/intermediate-rails-understanding-models-views-and-controllers/) stuff.

**Comment by armstrhb** [comment]
All controllers are added as of 6/13/15. Rest API is done, without authentication, in some parts. 

I'd say this issue can be closed, as this was more of a concept thing.
