### ISSUE TITLE
Realm Controller and Views

### ISSUE THREAD

**Issue by armstrhb** [armstrhb/Triumph#7]
We'll need controllers and views for the following:
- Realm List
- Realm Detail
- Creating a new Realm
- Editing a Realm
- Deleting a Realm

Let's also talk about the components for each. This will influence what the controller supplies, and the view formats and displays.

Here we go:
- [x] **Realm List**. The list should contain the realm name, number of users, number of achievements, admin group, total points? Clicking on a realm will link to the realm detail.
- [x] **Realm Detail**. A dashboard-like view of the realm. Show stats like number of achievements, number of users, total points. Total number of achievements gained. News things too: newest users, highest rep users, recent achievements.
- [x] **Creating a new Realm**. Should take place on the realm list (index) page. Modal pop up for creating a new form. Once form is created, listing is updated.
- [x] **Editing a Realm**. Done on the realm detail page. Modal pop up for editing. Details auto-update on page.
- [x] **Deleting a Realm**. Done on the realm detail page. Modal pop up confirming the deletion. If accepted, the user is redirected back to the listing page after the delete.

**Comment by armstrhb** [comment]
no assignee since this is a multi-person thing.  @wallBMW

**Comment by armstrhb** [comment]
Creating a new realm finished as of 6f98a8794c4e34b7aa809b512cd17fc6d2638c55.

**Comment by armstrhb** [comment]
Deleting a realm finished as of a47f7b1aa069b6c26d32c49ba03104e39a2c6405.

**Comment by armstrhb** [comment]
Editing a realm will probably need to wait until Realm Detail is up, at least in it's first revision.

**Comment by wallBMW** [comment]
Where are you thinking the achievement actions should take place? On the detail page or index page?

**Comment by armstrhb** [comment]
I'm actually writing up the blurb for the Achievement Controller now haha! I'm thinking this guy should exist within the realm, from a frontend standpoint.  So, we get to the achievements through the owning realm.

**Comment by armstrhb** [comment]
Just finished the first issue write up for Achievement Controller: #8

**Comment by armstrhb** [comment]
15f4f6a3bc0d65bb081fdf707815ef67baea80ed detail (controller side) is done.

**Comment by armstrhb** [comment]
1d23c9f29261860c9ba3c1d843adca2c2a032ab5 finished up realm edit.
